pipeline {
    agent any
    environment {
        MONGO_URI = "mongodb://root:example@mongodb:27017/mydatabase?authSource=admin"
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh 'npm test' // Adjust this if you have tests to run
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker-compose -f docker-compose.yml up -d'
                sh 'docker build -t my-node-app .'
                sh 'docker run -d -p 5000:5000 --env-file .env my-node-app'
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}

